# Generated by Django 5.0.8 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelemetryStudentEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("classroom_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("student_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("event_type", models.CharField(max_length=48)),
                ("source", models.CharField(default="classhub", max_length=40)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TelemetryStudentOutcomeEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("classroom_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("student_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("module_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("material_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("event_type", models.CharField(max_length=40)),
                ("source", models.CharField(default="classhub", max_length=40)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="telemetrystudentevent",
            index=models.Index(fields=["event_type", "created_at"], name="hbtm_evt_type_crt_idx"),
        ),
        migrations.AddIndex(
            model_name="telemetrystudentevent",
            index=models.Index(fields=["classroom_id", "created_at"], name="hbtm_evt_cls_crt_idx"),
        ),
        migrations.AddIndex(
            model_name="telemetrystudentevent",
            index=models.Index(fields=["student_id", "created_at"], name="hbtm_evt_stu_crt_idx"),
        ),
        migrations.AddIndex(
            model_name="telemetrystudentevent",
            index=models.Index(fields=["classroom_id", "event_type", "created_at"], name="hbtm_evt_clstypcrt_idx"),
        ),
        migrations.AddIndex(
            model_name="telemetrystudentoutcomeevent",
            index=models.Index(fields=["classroom_id", "event_type", "created_at"], name="hbtm_out_clstypcrt_idx"),
        ),
        migrations.AddIndex(
            model_name="telemetrystudentoutcomeevent",
            index=models.Index(fields=["student_id", "event_type", "created_at"], name="hbtm_out_stutypcrt_idx"),
        ),
        migrations.AddIndex(
            model_name="telemetrystudentoutcomeevent",
            index=models.Index(fields=["module_id", "event_type", "created_at"], name="hbtm_out_modtypcrt_idx"),
        ),
    ]

