# Generated by Django 5.0.8 on 2026-03-06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub_telemetry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telemetrystudentevent",
            name="core_event_id",
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="telemetrystudentoutcomeevent",
            name="core_outcome_event_id",
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="telemetrystudentevent",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="telemetrystudentoutcomeevent",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
