"""Compatibility export surface for hub.views.

New code should import endpoints from submodules by concern:
- hub.views.student
- hub.views.teacher
- hub.views.content
- hub.views.media
"""

from .content import course_lesson, course_overview, iter_course_lesson_options
from .internal import internal_helper_chat_access_event
from .media import lesson_asset_download, lesson_video_stream
from .student_join import index, invite_join, join_class
from .student import (
    healthz,
    material_checklist,
    material_reflection,
    material_upload,
    student_delete_work,
    student_end_session,
    student_home,
    student_logout,
    student_my_data,
    student_portfolio_export,
    student_return_code,
    submission_download,
)
from .teacher import (
    teach_add_material,
    teach_add_module,
    teach_assets,
    teach_class_dashboard,
    teach_class_join_card,
    teach_create_invite_link,
    teach_create_class,
    teach_create_teacher,
    teach_delete_student_data,
    teach_download_authoring_template,
    teach_disable_invite_link,
    teach_export_class_summary_csv,
    teach_export_class_submissions_today,
    teach_generate_authoring_templates,
    teach_home,
    teach_lessons,
    teach_lock_class,
    teach_login,
    teach_material_submissions,
    teach_merge_students,
    teach_module,
    teach_move_material,
    teach_move_module,
    teach_rename_student,
    teach_reset_helper_conversations,
    teach_reset_roster,
    teach_rotate_code,
    teach_set_lesson_release,
    teach_student_return_code,
    teach_teacher_2fa_setup,
    teach_toggle_lock,
    teach_videos,
    teacher_logout,
)

__all__ = [
    "course_lesson",
    "course_overview",
    "healthz",
    "index",
    "invite_join",
    "internal_helper_chat_access_event",
    "iter_course_lesson_options",
    "join_class",
    "lesson_asset_download",
    "lesson_video_stream",
    "material_checklist",
    "material_reflection",
    "material_upload",
    "student_delete_work",
    "student_end_session",
    "student_home",
    "student_logout",
    "student_my_data",
    "student_portfolio_export",
    "student_return_code",
    "submission_download",
    "teach_add_material",
    "teach_add_module",
    "teach_assets",
    "teach_class_dashboard",
    "teach_class_join_card",
    "teach_create_invite_link",
    "teach_create_class",
    "teach_create_teacher",
    "teach_delete_student_data",
    "teach_download_authoring_template",
    "teach_disable_invite_link",
    "teach_export_class_summary_csv",
    "teach_export_class_submissions_today",
    "teach_generate_authoring_templates",
    "teach_home",
    "teach_lessons",
    "teach_lock_class",
    "teach_login",
    "teach_material_submissions",
    "teach_merge_students",
    "teach_module",
    "teach_move_material",
    "teach_move_module",
    "teach_rename_student",
    "teach_reset_helper_conversations",
    "teach_reset_roster",
    "teach_rotate_code",
    "teach_set_lesson_release",
    "teach_student_return_code",
    "teach_teacher_2fa_setup",
    "teach_toggle_lock",
    "teach_videos",
    "teacher_logout",
]
