"""Compatibility export surface for hub.views.

New code should import endpoints from submodules by concern:
- hub.views.student
- hub.views.teacher
- hub.views.content
- hub.views.media
"""

from .api_student import api_student_modules, api_student_session, api_student_submissions
from .api_teacher import (
    api_teacher_classes,
    api_teacher_class_roster,
    api_teacher_class_submissions,
    api_teacher_rotate_code,
    api_teacher_set_enrollment_mode,
    api_teacher_toggle_lock,
)
from .content import course_lesson, course_overview, iter_course_lesson_options
from .internal import internal_helper_chat_access_event
from .media import lesson_asset_download, lesson_video_stream
from .student_join import index, invite_join, join_class
from .student import (
    healthz,
    material_upload,
    student_delete_work,
    student_end_session,
    student_home,
    student_logout,
    student_my_data,
    student_portfolio_export,
    student_return_code,
    submission_download,
    privacy_policy,
)
from .student_materials import material_checklist, material_reflection, material_rubric
from .teacher import (
    teach_add_material,
    teach_add_module,
    teach_assets,
    teach_certificate_eligibility,
    teach_class_dashboard,
    teach_class_join_card,
    teach_create_invite_link,
    teach_create_organization,
    teach_create_class,
    teach_create_teacher,
    teach_delete_student_data,
    teach_download_authoring_template,
    teach_export_syllabus,
    teach_download_certificate,
    teach_download_certificate_pdf,
    teach_disable_invite_link,
    teach_export_class_outcomes_csv,
    teach_export_class_summary_csv,
    teach_export_class_submissions_today,
    teach_generate_authoring_templates,
    teach_home,
    teach_import_syllabus_source,
    teach_lessons,
    teach_lock_class,
    teach_login,
    teach_issue_certificate,
    teach_mark_session_completed,
    teach_material_submissions,
    teach_merge_students,
    teach_module,
    teach_move_material,
    teach_move_module,
    teach_change_password,
    teach_rename_student,
    teach_reset_helper_conversations,
    teach_reset_roster,
    teach_rotate_code,
    teach_update_class_landing,
    teach_set_enrollment_mode,
    teach_set_organization_active,
    teach_set_lesson_release,
    teach_student_return_code,
    teach_teacher_2fa_setup,
    teach_toggle_lock,
    teach_update_profile,
    teach_upsert_organization_membership,
    teach_videos,
    teacher_logout,
)

__all__ = [
    "api_student_modules",
    "api_student_session",
    "api_student_submissions",
    "api_teacher_classes",
    "api_teacher_class_roster",
    "api_teacher_class_submissions",
    "api_teacher_rotate_code",
    "api_teacher_set_enrollment_mode",
    "api_teacher_toggle_lock",
    "course_lesson",
    "course_overview",
    "healthz",
    "index",
    "invite_join",
    "internal_helper_chat_access_event",
    "iter_course_lesson_options",
    "join_class",
    "lesson_asset_download",
    "lesson_video_stream",
    "material_checklist",
    "material_reflection",
    "material_rubric",
    "material_upload",
    "student_delete_work",
    "student_end_session",
    "student_home",
    "student_logout",
    "student_my_data",
    "student_portfolio_export",
    "student_return_code",
    "submission_download",
    "privacy_policy",
    "teach_add_material",
    "teach_add_module",
    "teach_assets",
    "teach_certificate_eligibility",
    "teach_class_dashboard",
    "teach_class_join_card",
    "teach_update_class_landing",
    "teach_create_invite_link",
    "teach_create_organization",
    "teach_create_class",
    "teach_create_teacher",
    "teach_delete_student_data",
    "teach_download_authoring_template",
    "teach_export_syllabus",
    "teach_download_certificate",
    "teach_download_certificate_pdf",
    "teach_disable_invite_link",
    "teach_export_class_outcomes_csv",
    "teach_export_class_summary_csv",
    "teach_export_class_submissions_today",
    "teach_generate_authoring_templates",
    "teach_import_syllabus_source",
    "teach_home",
    "teach_lessons",
    "teach_lock_class",
    "teach_login",
    "teach_issue_certificate",
    "teach_mark_session_completed",
    "teach_material_submissions",
    "teach_merge_students",
    "teach_module",
    "teach_move_material",
    "teach_move_module",
    "teach_change_password",
    "teach_rename_student",
    "teach_reset_helper_conversations",
    "teach_reset_roster",
    "teach_rotate_code",
    "teach_set_enrollment_mode",
    "teach_set_organization_active",
    "teach_set_lesson_release",
    "teach_student_return_code",
    "teach_teacher_2fa_setup",
    "teach_toggle_lock",
    "teach_update_profile",
    "teach_upsert_organization_membership",
    "teach_videos",
    "teacher_logout",
]
