"""Compatibility export surface for hub.views.

New code should import endpoints from submodules by concern:
- hub.views.student
- hub.views.teacher
- hub.views.content
- hub.views.media
"""

from .api_student import api_student_modules, api_student_session, api_student_submissions
from .api_student_upload import api_student_csrf, api_student_material_upload
from .api_teacher import (
    api_teacher_classes,
    api_teacher_class_roster,
    api_teacher_class_submissions,
    api_teacher_rotate_code,
    api_teacher_set_enrollment_mode,
    api_teacher_toggle_lock,
)
from .api_teacher_rbac import api_teacher_rbac_simulate
from .content import course_lesson, course_overview, iter_course_lesson_options
from .internal import internal_helper_chat_access_event
from .media import lesson_asset_download, lesson_video_stream
from .student_join import index, invite_join, join_class
from .student_identity import student_rename_display_name
from .student_artifacts import (
    student_gallery_wall,
    student_portfolio,
    student_set_submission_publish,
)
from .student import (
    healthz,
    material_upload,
    student_delete_work,
    student_end_session,
    student_home,
    student_logout,
    student_my_data,
    student_portfolio_export,
    student_return_code,
    submission_download,
    privacy_policy,
    trust_page,
)
from .student_micro_checks import student_micro_check
from .student_materials import material_checklist, material_reflection, material_rubric
from .student_sync import student_shell_manifest, student_upload_sync_service_worker
from .teacher import (
    teach_add_material,
    teach_add_support_tag,
    teach_add_module,
    teach_assets,
    teach_certificate_eligibility,
    teach_class_dashboard,
    teach_class_join_card,
    teach_create_invite_link,
    teach_create_organization,
    teach_rename_organization,
    teach_set_class_organization,
    teach_upsert_org_role_capability,
    teach_bulk_set_class_staff_assignments,
    teach_create_class,
    teach_create_teacher,
    teach_reset_teacher_account_password,
    teach_resend_teacher_invite,
    teach_set_teacher_account_active,
    teach_set_teacher_account_superuser,
    teach_delete_student_data,
    teach_download_authoring_template,
    teach_export_syllabus,
    teach_data_lifespan,
    teach_download_certificate,
    teach_download_certificate_pdf,
    teach_disable_invite_link,
    teach_export_class_outcomes_csv,
    teach_export_class_summary_csv,
    teach_export_class_submissions_today,
    teach_export_rbac_policy,
    teach_generate_authoring_templates,
    teach_home,
    teach_import_rbac_policy,
    teach_import_syllabus_source,
    teach_lessons,
    teach_lock_class,
    teach_login,
    teach_issue_certificate,
    teach_mark_session_completed,
    teach_material_submissions,
    teach_moderate_gallery_submission,
    teach_merge_students,
    teach_module,
    teach_move_material,
    teach_move_module,
    teach_change_password,
    teach_rename_student,
    teach_resolve_delete_request,
    teach_resolve_stuck_flag,
    teach_reset_helper_conversations,
    teach_reset_roster,
    teach_rotate_code,
    teach_remove_support_tag,
    teach_review_rbac_change_request,
    teach_set_module_scope_grant_active,
    teach_simulate_rbac_access,
    teach_upsert_custom_role,
    teach_upsert_custom_role_assignment,
    teach_upsert_custom_role_capability,
    teach_upsert_module_scope_grant,
    teach_update_class_landing,
    teach_set_enrollment_mode,
    teach_set_module_gallery_enabled,
    teach_set_organization_active,
    teach_set_retention_preset,
    teach_set_lesson_release,
    teach_student_return_code,
    teach_teacher_2fa_setup,
    teach_toggle_lock,
    teach_upsert_class_staff_assignment,
    teach_update_profile,
    teach_upsert_organization_membership,
    teach_videos,
    teacher_logout,
)

__all__ = [
    "api_student_csrf",
    "api_student_material_upload",
    "api_student_modules",
    "api_student_session",
    "api_student_submissions",
    "api_teacher_classes",
    "api_teacher_class_roster",
    "api_teacher_class_submissions",
    "api_teacher_rbac_simulate",
    "api_teacher_rotate_code",
    "api_teacher_set_enrollment_mode",
    "api_teacher_toggle_lock",
    "course_lesson",
    "course_overview",
    "healthz",
    "index",
    "invite_join",
    "internal_helper_chat_access_event",
    "iter_course_lesson_options",
    "join_class",
    "lesson_asset_download",
    "lesson_video_stream",
    "material_checklist",
    "material_reflection",
    "material_rubric",
    "material_upload",
    "student_delete_work",
    "student_end_session",
    "student_home",
    "student_logout",
    "student_micro_check",
    "student_my_data",
    "student_portfolio",
    "student_portfolio_export",
    "student_gallery_wall",
    "student_rename_display_name",
    "student_set_submission_publish",
    "student_shell_manifest",
    "student_return_code",
    "student_upload_sync_service_worker",
    "submission_download",
    "privacy_policy",
    "trust_page",
    "teach_add_material",
    "teach_add_module",
    "teach_assets",
    "teach_certificate_eligibility",
    "teach_class_dashboard",
    "teach_class_join_card",
    "teach_add_support_tag",
    "teach_remove_support_tag",
    "teach_update_class_landing",
    "teach_create_invite_link",
    "teach_create_organization",
    "teach_rename_organization",
    "teach_set_class_organization",
    "teach_upsert_org_role_capability",
    "teach_upsert_class_staff_assignment",
    "teach_bulk_set_class_staff_assignments",
    "teach_create_class",
    "teach_create_teacher",
    "teach_set_teacher_account_active",
    "teach_set_teacher_account_superuser",
    "teach_reset_teacher_account_password",
    "teach_resend_teacher_invite",
    "teach_delete_student_data",
    "teach_download_authoring_template",
    "teach_export_syllabus",
    "teach_data_lifespan",
    "teach_download_certificate",
    "teach_download_certificate_pdf",
    "teach_disable_invite_link",
    "teach_export_class_outcomes_csv",
    "teach_export_class_summary_csv",
    "teach_export_class_submissions_today",
    "teach_export_rbac_policy",
    "teach_generate_authoring_templates",
    "teach_import_syllabus_source",
    "teach_import_rbac_policy",
    "teach_home",
    "teach_lessons",
    "teach_upsert_module_scope_grant",
    "teach_set_module_scope_grant_active",
    "teach_simulate_rbac_access",
    "teach_upsert_custom_role",
    "teach_upsert_custom_role_capability",
    "teach_upsert_custom_role_assignment",
    "teach_review_rbac_change_request",
    "teach_lock_class",
    "teach_login",
    "teach_issue_certificate",
    "teach_mark_session_completed",
    "teach_material_submissions",
    "teach_moderate_gallery_submission",
    "teach_merge_students",
    "teach_module",
    "teach_move_material",
    "teach_move_module",
    "teach_change_password",
    "teach_rename_student",
    "teach_resolve_delete_request",
    "teach_resolve_stuck_flag",
    "teach_reset_helper_conversations",
    "teach_reset_roster",
    "teach_rotate_code",
    "teach_set_enrollment_mode",
    "teach_set_module_gallery_enabled",
    "teach_set_organization_active",
    "teach_set_retention_preset",
    "teach_set_lesson_release",
    "teach_student_return_code",
    "teach_teacher_2fa_setup",
    "teach_toggle_lock",
    "teach_update_profile",
    "teach_upsert_organization_membership",
    "teach_videos",
    "teacher_logout",
]
