# Generated by Django 5.0.8 on 2026-01-16 21:00

import django.db.models.deletion
import hub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('join_code', models.CharField(default=hub.models.gen_class_code, max_length=16, unique=True)),
                ('is_locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='hub.class')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('link', 'Link'), ('text', 'Text'), ('upload', 'Upload')], default='link', max_length=16)),
                ('url', models.URLField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('accepted_extensions', models.CharField(blank=True, default='', max_length=200)),
                ('max_upload_mb', models.PositiveIntegerField(default=50)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='hub.module')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='hub.class')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(upload_to=hub.models._submission_upload_to)),
                ('note', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='hub.material')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='hub.studentidentity')),
            ],
            options={
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
    ]
