# Generated by Django 5.0.8 on 2026-02-16

import secrets

import hub.models
from django.db import migrations, models


def _gen_code(length: int = 6) -> str:
    alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def _backfill_return_codes(apps, schema_editor):
    StudentIdentity = apps.get_model("hub", "StudentIdentity")
    seen: set[tuple[int, str]] = set()

    for student in StudentIdentity.objects.all().only("id", "classroom_id", "return_code"):
        current = (student.return_code or "").strip().upper()
        key = (student.classroom_id, current) if current else None

        if current and key not in seen:
            seen.add(key)
            if current != student.return_code:
                student.return_code = current
                student.save(update_fields=["return_code"])
            continue

        for _ in range(20):
            candidate = _gen_code()
            key = (student.classroom_id, candidate)
            if key in seen:
                continue
            seen.add(key)
            student.return_code = candidate
            student.save(update_fields=["return_code"])
            break
        else:
            raise RuntimeError("could_not_allocate_unique_student_return_code")


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0003_lessonrelease"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentidentity",
            name="return_code",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
        migrations.RunPython(_backfill_return_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="studentidentity",
            name="return_code",
            field=models.CharField(default=hub.models.gen_student_return_code, max_length=12),
        ),
        migrations.AddConstraint(
            model_name="studentidentity",
            constraint=models.UniqueConstraint(
                fields=("classroom", "return_code"),
                name="uniq_student_return_code_per_class",
            ),
        ),
        migrations.AddIndex(
            model_name="studentidentity",
            index=models.Index(fields=["classroom", "display_name"], name="hub_studeni_classro_11dfba_idx"),
        ),
        migrations.AddIndex(
            model_name="studentidentity",
            index=models.Index(fields=["classroom", "return_code"], name="hub_studeni_classro_3c11ef_idx"),
        ),
    ]
