# Generated by Django 5.0.8 on 2026-02-16

import django.db.models.deletion
import hub.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0004_studentidentity_return_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonAssetFolder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(default="general", max_length=200, unique=True)),
                ("display_name", models.CharField(blank=True, default="", max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["path", "id"],
            },
        ),
        migrations.CreateModel(
            name="LessonAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("course_slug", models.SlugField(blank=True, default="", max_length=120)),
                ("lesson_slug", models.SlugField(blank=True, default="", max_length=120)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("original_filename", models.CharField(blank=True, default="", max_length=255)),
                ("file", models.FileField(upload_to=hub.models._lesson_asset_upload_to)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="hub.lessonassetfolder",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="lessonasset",
            index=models.Index(fields=["folder", "is_active"], name="hub_lessona_folder__764626_idx"),
        ),
        migrations.AddIndex(
            model_name="lessonasset",
            index=models.Index(
                fields=["course_slug", "lesson_slug", "is_active"],
                name="hub_lessona_course__7a0ed8_idx",
            ),
        ),
    ]
