# Generated by Django 5.1.6 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0013_organization_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="enrollment_mode",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("invite_only", "Invite only"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
