# Generated by Django 5.1.6 on 2026-02-26 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0014_class_enrollment_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentOutcomeEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("session_completed", "Session completed"),
                            ("artifact_submitted", "Artifact submitted"),
                            ("milestone_earned", "Milestone earned"),
                        ],
                        max_length=40,
                    ),
                ),
                ("source", models.CharField(default="classhub", max_length=40)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_outcome_events",
                        to="hub.class",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_outcome_events",
                        to="hub.material",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_outcome_events",
                        to="hub.module",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outcome_events",
                        to="hub.studentidentity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="studentoutcomeevent",
            index=models.Index(fields=["classroom", "event_type", "created_at"], name="hub_stout_cl_evt_cra_idx"),
        ),
        migrations.AddIndex(
            model_name="studentoutcomeevent",
            index=models.Index(fields=["student", "event_type", "created_at"], name="hub_stout_st_evt_cra_idx"),
        ),
        migrations.AddIndex(
            model_name="studentoutcomeevent",
            index=models.Index(fields=["module", "event_type", "created_at"], name="hub_stout_mod_evt_cra_idx"),
        ),
    ]
