# Generated by Django 5.2.11 on 2026-02-26 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0015_studentoutcomeevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="type",
            field=models.CharField(
                choices=[
                    ("link", "Link"),
                    ("text", "Text"),
                    ("upload", "Upload"),
                    ("checklist", "Checklist"),
                    ("reflection", "Reflection"),
                ],
                default="link",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="StudentMaterialResponse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("checklist_checked", models.JSONField(blank=True, default=list)),
                ("reflection_text", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_responses",
                        to="hub.material",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_responses",
                        to="hub.studentidentity",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="studentmaterialresponse",
            constraint=models.UniqueConstraint(
                fields=("material", "student"),
                name="uniq_material_response_per_student",
            ),
        ),
        migrations.AddIndex(
            model_name="studentmaterialresponse",
            index=models.Index(fields=["material", "student"], name="hub_matresp_matstu_3a9b_idx"),
        ),
        migrations.AddIndex(
            model_name="studentmaterialresponse",
            index=models.Index(fields=["student", "updated_at"], name="hub_matresp_stupd_7f2c_idx"),
        ),
    ]
