# Generated by Django 5.2.11 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0016_material_response_and_material_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="type",
            field=models.CharField(
                choices=[
                    ("link", "Link"),
                    ("text", "Text"),
                    ("upload", "Upload"),
                    ("gallery", "Gallery"),
                    ("checklist", "Checklist"),
                    ("reflection", "Reflection"),
                ],
                default="link",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="is_gallery_shared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["material", "is_gallery_shared", "uploaded_at"], name="hub_submis_matshr_90a5_idx"),
        ),
    ]
