# Generated by Django 5.2.11 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0017_gallery_material_type_and_share_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="type",
            field=models.CharField(
                choices=[
                    ("link", "Link"),
                    ("text", "Text"),
                    ("upload", "Upload"),
                    ("gallery", "Gallery"),
                    ("checklist", "Checklist"),
                    ("reflection", "Reflection"),
                    ("rubric", "Rubric"),
                ],
                default="link",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="rubric_scale_max",
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name="studentmaterialresponse",
            name="rubric_feedback",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="studentmaterialresponse",
            name="rubric_scores",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
