# Generated by Django 5.2.11 on 2026-02-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0018_rubric_material_type_and_responses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassStaffAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_assignments",
                        to="hub.class",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classhub_class_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["classroom_id", "user_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="classstaffassignment",
            constraint=models.UniqueConstraint(fields=("classroom", "user"), name="uniq_class_staff_assignment"),
        ),
        migrations.AddIndex(
            model_name="classstaffassignment",
            index=models.Index(fields=["classroom", "is_active"], name="hub_clsasg_clsact_91f3_idx"),
        ),
        migrations.AddIndex(
            model_name="classstaffassignment",
            index=models.Index(fields=["user", "is_active"], name="hub_clsasg_usract_b03a_idx"),
        ),
    ]
