# Generated by Django 5.2.11 on 2026-02-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import hub.models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0019_classstaffassignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateIssuance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(default=hub.models.gen_certificate_code, max_length=24, unique=True)),
                ("signed_token", models.TextField(blank=True, default="")),
                ("session_count", models.PositiveIntegerField(default=0)),
                ("artifact_count", models.PositiveIntegerField(default=0)),
                ("milestone_count", models.PositiveIntegerField(default=0)),
                ("min_sessions_required", models.PositiveIntegerField(default=1)),
                ("min_artifacts_required", models.PositiveIntegerField(default=1)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_issuances",
                        to="hub.class",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_issuances",
                        to="hub.studentidentity",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="certificateissuance",
            constraint=models.UniqueConstraint(
                fields=("classroom", "student"),
                name="uniq_certificate_per_student_class",
            ),
        ),
        migrations.AddIndex(
            model_name="certificateissuance",
            index=models.Index(fields=["classroom", "issued_at"], name="hub_cert_clsiss_1d1b_idx"),
        ),
        migrations.AddIndex(
            model_name="certificateissuance",
            index=models.Index(fields=["student", "issued_at"], name="hub_cert_stuiss_67e4_idx"),
        ),
    ]
