# Generated by Django 5.2.11 on 2026-02-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0020_certificateissuance"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="student_landing_hero_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="class",
            name="student_landing_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="class",
            name="student_landing_title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
