# Generated by Django 5.2.11 on 2026-03-04 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0026_classstaffmodulescopegrant_effect'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRoleCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('teacher', 'Teacher'), ('viewer', 'Viewer')], max_length=20)),
                ('capability', models.CharField(choices=[('class.view', 'Class view'), ('class.manage', 'Class manage'), ('class.create', 'Class create'), ('roster.manage', 'Roster manage'), ('submission.view', 'Submission view'), ('submission.delete', 'Submission delete'), ('policy.manage', 'Policy manage'), ('syllabus.export', 'Syllabus export')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_capabilities', to='hub.organization')),
            ],
            options={
                'ordering': ['organization_id', 'role', 'capability'],
                'indexes': [models.Index(fields=['organization', 'role', 'is_active'], name='hub_orgrole_orgrol_1f5a_idx'), models.Index(fields=['organization', 'capability', 'is_active'], name='hub_orgrole_orgcap_79bc_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'role', 'capability'), name='uniq_org_role_capability')],
            },
        ),
    ]
