# Generated by Django 5.2.11 on 2026-03-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0027_organizationrolecapability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classstaffmodulescopegrant',
            name='capability',
            field=models.CharField(choices=[('submission.view', 'Submission view'), ('submission.delete', 'Submission delete'), ('roster.manage', 'Roster manage'), ('policy.manage', 'Policy manage')], max_length=40),
        ),
    ]
