# Generated by Django 5.2.11 on 2026-03-05 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0028_alter_classstaffmodulescopegrant_capability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='hub.organization')),
            ],
            options={
                'ordering': ['organization_id', 'slug', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationCustomRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_role_assignments', to='hub.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hub.organizationcustomrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classhub_custom_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization_id', 'user_id', 'role_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationCustomRoleCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(choices=[('class.view', 'Class view'), ('class.manage', 'Class manage'), ('class.create', 'Class create'), ('roster.manage', 'Roster manage'), ('submission.view', 'Submission view'), ('submission.delete', 'Submission delete'), ('policy.manage', 'Policy manage'), ('syllabus.export', 'Syllabus export')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='hub.organizationcustomrole')),
            ],
            options={
                'ordering': ['role_id', 'capability', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='organizationcustomrole',
            index=models.Index(fields=['organization', 'is_active'], name='hub_crole_orgact_9f33_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationcustomrole',
            index=models.Index(fields=['organization', 'slug'], name='hub_crole_orgslug_2f3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationcustomrole',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='uniq_org_custom_role_slug'),
        ),
        migrations.AddIndex(
            model_name='organizationcustomroleassignment',
            index=models.Index(fields=['organization', 'user', 'is_active'], name='hub_croleasg_orgusr_514f_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationcustomroleassignment',
            index=models.Index(fields=['role', 'is_active'], name='hub_croleasg_roleac_c050_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationcustomroleassignment',
            constraint=models.UniqueConstraint(fields=('organization', 'user', 'role'), name='uniq_org_custom_role_assignment'),
        ),
        migrations.AddIndex(
            model_name='organizationcustomrolecapability',
            index=models.Index(fields=['role', 'is_active'], name='hub_crolecap_roleac_20bb_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationcustomrolecapability',
            index=models.Index(fields=['capability', 'is_active'], name='hub_crolecap_capact_7d3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationcustomrolecapability',
            constraint=models.UniqueConstraint(fields=('role', 'capability'), name='uniq_custom_role_capability'),
        ),
    ]
