# Generated by Django 5.2.11 on 2026-03-05 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0029_organizationcustomrole_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RbacPolicyChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('scope_grant_upsert', 'Scoped grant upsert'), ('scope_grant_set_active', 'Scoped grant set active'), ('custom_role_upsert', 'Custom role upsert'), ('custom_role_capability_upsert', 'Custom role capability upsert'), ('custom_role_assignment_upsert', 'Custom role assignment upsert'), ('policy_import', 'Policy import')], max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('review_note', models.CharField(blank=True, default='', max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_policy_change_requests', to='hub.class')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbac_policy_change_requests', to='hub.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classhub_rbac_policy_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classhub_rbac_policy_change_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='hub_rbacreq_statcrt_c17a_idx'), models.Index(fields=['request_type', 'status'], name='hub_rbacreq_typsta_d522_idx'), models.Index(fields=['organization', 'status'], name='hub_rbacreq_orgsta_7ba7_idx'), models.Index(fields=['classroom', 'status'], name='hub_rbacreq_clssta_8a2b_idx'), models.Index(fields=['requested_by', 'status'], name='hub_rbacreq_usrsta_5f3e_idx')],
            },
        ),
    ]
