# Generated by Django 5.2.11 on 2026-03-12 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0030_rbacpolicychangerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="student_landing_default_module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hub.module",
            ),
        ),
    ]
