# Generated by Django 5.2.12 on 2026-04-12 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0031_class_student_landing_default_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLessonOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_slug', models.CharField(max_length=200)),
                ('lesson_slug', models.CharField(max_length=200)),
                ('raw_markdown', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_overrides', to='hub.class')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classhub_lesson_overrides_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['classroom', 'course_slug', 'lesson_slug'], name='hub_lessonov_cls_8b0a_idx')],
                'constraints': [models.UniqueConstraint(fields=('classroom', 'course_slug', 'lesson_slug'), name='uniq_classroom_lesson_override')],
            },
        ),
    ]
