# Generated by Django 5.2.16 on 2026-07-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0032_classlessonoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Class-scoped owner'), ('admin', 'Class-scoped admin'), ('teacher', 'Teacher'), ('viewer', 'Viewer')], default='teacher', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationrolecapability',
            name='role',
            field=models.CharField(choices=[('owner', 'Class-scoped owner'), ('admin', 'Class-scoped admin'), ('teacher', 'Teacher'), ('viewer', 'Viewer')], max_length=20),
        ),
    ]
