from .engine import heuristics as engine_heuristics
from .engine import reference as engine_reference
from .engine import service as engine_service
from .views_chat_helpers import DEFAULT_TEXT_LANGUAGE_KEYWORDS


def build_chat_deps(
    *,
    json_response_fn,
    log_chat_event_fn,
    env_int_fn,
    env_float_fn,
    env_bool_fn,
    redact_fn,
    load_scope_from_token_fn,
    load_reference_text_fn,
    load_reference_chunks_fn,
    is_piper_context_fn,
    is_piper_hardware_question_fn,
    build_piper_hardware_triage_text_fn,
    build_instructions_fn,
    backend_circuit_is_open_fn,
    call_backend_with_retries_fn,
    record_backend_failure_fn,
    reset_backend_failure_state_fn,
    acquire_slot_fn,
    release_slot_fn,
    truncate_response_text_fn,
    normalize_conversation_id_fn,
    scope_fingerprint_fn,
    load_conversation_state_fn,
    save_conversation_state_fn,
    compact_conversation_fn,
    clear_conversation_turns_fn,
    format_conversation_for_prompt_fn,
    classify_intent_fn,
    build_follow_up_suggestions_fn,
):
    deps = engine_service.ChatDeps(
        json_response=json_response_fn,
        log_chat_event=log_chat_event_fn,
        env_int=env_int_fn,
        env_float=env_float_fn,
        env_bool=env_bool_fn,
        redact=redact_fn,
        load_scope_from_token=load_scope_from_token_fn,
        resolve_reference_file=engine_reference.resolve_reference_file,
        load_reference_text=load_reference_text_fn,
        load_reference_chunks=load_reference_chunks_fn,
        build_reference_citations=engine_reference.build_reference_citations,
        format_reference_citations_for_prompt=engine_reference.format_reference_citations_for_prompt,
        parse_csv_list=engine_heuristics.parse_csv_list,
        contains_text_language=engine_heuristics.contains_text_language,
        is_scratch_context=engine_heuristics.is_scratch_context,
        is_piper_context=is_piper_context_fn,
        is_piper_hardware_question=is_piper_hardware_question_fn,
        build_piper_hardware_triage_text=build_piper_hardware_triage_text_fn,
        allowed_topic_overlap=engine_heuristics.allowed_topic_overlap,
        build_instructions=build_instructions_fn,
        backend_circuit_is_open=backend_circuit_is_open_fn,
        call_backend_with_retries=call_backend_with_retries_fn,
        record_backend_failure=record_backend_failure_fn,
        reset_backend_failure_state=reset_backend_failure_state_fn,
        acquire_slot=acquire_slot_fn,
        release_slot=release_slot_fn,
        truncate_response_text=truncate_response_text_fn,
        normalize_conversation_id=normalize_conversation_id_fn,
        scope_fingerprint=scope_fingerprint_fn,
        load_conversation_state=load_conversation_state_fn,
        save_conversation_state=save_conversation_state_fn,
        compact_conversation=compact_conversation_fn,
        clear_conversation_turns=clear_conversation_turns_fn,
        format_conversation_for_prompt=format_conversation_for_prompt_fn,
        classify_intent=classify_intent_fn,
        build_follow_up_suggestions=build_follow_up_suggestions_fn,
    )
    return deps


__all__ = ["DEFAULT_TEXT_LANGUAGE_KEYWORDS", "build_chat_deps"]
