#!/usr/bin/env python3
"""Create a blank evidence pack for the operator onboarding drill."""

from __future__ import annotations

import argparse
import socket
from datetime import date
from pathlib import Path
from textwrap import dedent

DEFAULT_DATE = date.today().isoformat()
DEFAULT_OUT_DIR = Path("artifacts") / "stability" / DEFAULT_DATE / "operator_onboarding_drill"
DEFAULT_TURNOVER_LOG_PATH = Path("docs") / "TURNOVER_DRILL_LOG.md"


def _build_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out-dir",
        default=str(DEFAULT_OUT_DIR),
        help="Output directory for the drill evidence pack "
        f"(default: {DEFAULT_OUT_DIR.as_posix()})",
    )
    parser.add_argument("--operator", default="", help="Operator name to prefill in the markdown log")
    parser.add_argument("--environment", default="", help="Environment label to prefill in the markdown log")
    parser.add_argument("--host", default=socket.gethostname(), help="Host label to prefill in the markdown log")
    parser.add_argument(
        "--next-drill-date",
        default="",
        help="Optional next turnover-drill date for the generated TURNOVER_DRILL_LOG row stub",
    )
    parser.add_argument(
        "--append-turnover-log",
        action="store_true",
        help="Append the generated row into docs/TURNOVER_DRILL_LOG.md instead of only writing the row stub file",
    )
    parser.add_argument(
        "--turnover-log-path",
        default=str(DEFAULT_TURNOVER_LOG_PATH),
        help="Path to the canonical turnover drill log when using --append-turnover-log "
        f"(default: {DEFAULT_TURNOVER_LOG_PATH.as_posix()})",
    )
    parser.add_argument("--force", action="store_true", help="Overwrite existing stub files in the output directory")
    return parser


def _write_text(path: Path, text: str, *, force: bool) -> None:
    if path.exists() and not force:
        return
    path.write_text(text, encoding="utf-8")


def _log_template(*, operator: str, host: str, environment: str, out_dir: Path) -> str:
    snapshot_command = (
        "DJANGO_DEBUG=1 DJANGO_SECRET_KEY=test-secret .venv_test/bin/python "
        "services/classhub/manage.py export_remote_compute_operator_snapshot"
    )
    retention_command = (
        "bash scripts/retention_health_snapshot.sh --compose-mode prod --out "
        f"{out_dir.as_posix()}/retention_health.log"
    )
    return dedent(
        f"""\
        # Operator Onboarding Drill Log

        - Date: {DEFAULT_DATE}
        - Operator: {operator}
        - Host: {host}
        - Environment: {environment}

        ## Step 1 — System doctor
        - Command: `bash scripts/system_doctor.sh`
        - Result:
        - Evidence file: `operator_onboarding_doctor.log`

        ## Step 2 — Smoke
        - Command: `bash scripts/smoke_check.sh --strict`
        - Result:
        - Evidence file: `operator_onboarding_smoke.log`

        ## Step 3 — Remote-compute operator snapshot
        - Command: `{snapshot_command}`
        - Aggregate signal:
        - What it means:
        - Evidence file: `remote_compute_operator_snapshot.json`

        ## Step 4 — Retention evidence
        - Command: `{retention_command}`
        - Timer state:
        - Dry-run result:
        - Evidence file: `retention_health.log`

        ## Step 5 — Token rotation lookup
        - Secret involved:
        - Correct doc section:
        - Rotation impact in one sentence:

        ## Step 6 — Current remote-compute state explanation
        - Current signal level:
        - Students affected?
        - What should staff do now?

        ## Step 7 — Degraded-helper triage
        - Probe command: `bash scripts/check_llm_backend.sh --probe-chat`
        - Outcome:
        - Is local/default helper still available?
        - Next operator action:

        ## Step 8 — Class-scoped export path
        - Example class id:
        - Export URL or command:

        ## Step 9 — Canonical docs when claims conflict
        - Which docs are canonical here:
        - Why:

        ## Operator got stuck here
        - Step:
        - Symptom:
        - What was unclear:
        - What should become a calmer artifact:
        """
    )


def _instructions_template(*, out_dir: Path) -> str:
    return dedent(
        f"""\
        # Operator Onboarding Drill Pack

        This directory was generated by:

        ```bash
        python3 scripts/init_operator_onboarding_drill.py --out-dir {out_dir.as_posix()}
        ```

        Optional convenience:

        ```bash
        python3 scripts/init_operator_onboarding_drill.py --append-turnover-log
        ```

        That mode updates `docs/TURNOVER_DRILL_LOG.md` directly using the same generated row stub.

        Fill in these files as you run the drill:

        - `operator_onboarding_log.md`
        - `operator_onboarding_doctor.log`
        - `operator_onboarding_smoke.log`
        - `remote_compute_operator_snapshot.json`
        - `retention_health.log`
        - `degraded_helper_triage.md`
        - `turnover_drill_log_row.md`

        Canonical drill doc:

        - `docs/OPERATOR_ONBOARDING_DRILL.md`
        - `docs/TURNOVER_DRILL_LOG.md`
        """
    )


def _stub_file(title: str, command: str) -> str:
    return f"""# {title}

Expected command:

```bash
{command}
```

Paste the command output or your notes below.
"""


def _human_date_today() -> str:
    today = date.today()
    return f"{today.strftime('%B')} {today.day}, {today.year}"


def _turnover_drill_row(*, operator: str, out_dir: Path, next_drill_date: str) -> str:
    operator_value = operator or "name(s)"
    next_value = next_drill_date or "YYYY-MM-DD"
    artifact_path = out_dir.relative_to(Path.cwd()) if out_dir.is_relative_to(Path.cwd()) else out_dir
    return (
        "| "
        f"{DEFAULT_DATE} | "
        f"{operator_value} | "
        "PASS/FAIL | "
        "PASS/FAIL | "
        "yes/no | "
        "short list | "
        "yes/no | "
        f"`{artifact_path.as_posix()}/` | "
        f"{next_value} | "
        "operator onboarding drill summary |"
    )


def _append_turnover_log(*, turnover_log_path: Path, row: str) -> str:
    if not turnover_log_path.exists():
        raise FileNotFoundError(f"missing turnover log: {turnover_log_path}")
    text = turnover_log_path.read_text(encoding="utf-8")
    if row in text:
        return "already_present"

    updated_text = text
    placeholder_row = (
        "| YYYY-MM-DD | names | PASS/FAIL | PASS/FAIL | yes/no | short list | yes/no | "
        "`artifacts/stability/<date>/` | YYYY-MM-DD | drill summary |"
    )
    if placeholder_row in updated_text:
        updated_text = updated_text.replace(placeholder_row, f"{row}\n{placeholder_row}", 1)
    elif "\n## Acceptance Rule" in updated_text:
        updated_text = updated_text.replace("\n## Acceptance Rule", f"\n{row}\n\n## Acceptance Rule", 1)
    else:
        updated_text = updated_text.rstrip() + f"\n{row}\n"

    last_updated_prefix = "Last updated: "
    if last_updated_prefix in updated_text:
        start = updated_text.index(last_updated_prefix)
        end = updated_text.find("\n", start)
        if end == -1:
            end = len(updated_text)
        updated_text = updated_text[:start] + f"{last_updated_prefix}{_human_date_today()}" + updated_text[end:]

    turnover_log_path.write_text(updated_text, encoding="utf-8")
    return "appended"


def main() -> int:
    parser = _build_argument_parser()
    args = parser.parse_args()

    out_dir = Path(args.out_dir).resolve()
    turnover_log_path = Path(args.turnover_log_path).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    row = _turnover_drill_row(
        operator=str(args.operator or "").strip(),
        out_dir=out_dir,
        next_drill_date=str(args.next_drill_date or "").strip(),
    )

    _write_text(
        out_dir / "operator_onboarding_log.md",
        _log_template(
            operator=str(args.operator or "").strip(),
            host=str(args.host or "").strip(),
            environment=str(args.environment or "").strip(),
            out_dir=out_dir,
        ),
        force=args.force,
    )
    _write_text(out_dir / "README.md", _instructions_template(out_dir=out_dir), force=args.force)
    _write_text(
        out_dir / "operator_onboarding_doctor.log",
        _stub_file("System Doctor Output", "bash scripts/system_doctor.sh"),
        force=args.force,
    )
    _write_text(
        out_dir / "operator_onboarding_smoke.log",
        _stub_file("Smoke Output", "bash scripts/smoke_check.sh --strict"),
        force=args.force,
    )
    _write_text(
        out_dir / "degraded_helper_triage.md",
        _stub_file("Degraded Helper Triage Notes", "bash scripts/check_llm_backend.sh --probe-chat"),
        force=args.force,
    )
    _write_text(
        out_dir / "turnover_drill_log_row.md",
        dedent(
            f"""\
            # TURNOVER_DRILL_LOG Row Stub

            Paste this row into `docs/TURNOVER_DRILL_LOG.md` after the drill is complete:

            {row}
            """
        ),
        force=args.force,
    )
    append_status = ""
    if args.append_turnover_log:
        append_status = _append_turnover_log(turnover_log_path=turnover_log_path, row=row)

    print(f"[operator-onboarding-drill] wrote {out_dir}")
    if args.append_turnover_log:
        print(f"[operator-onboarding-drill] turnover log {append_status}: {turnover_log_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
